Prüfschritte/de/11.8.2 Barrierefreie Erstellung von Inhalten.adoc
Unklar ist mir bislang, inwieweit aus dem Prüfschritt Vorgaben nicht nur für die Ausgabe, sondern auch für das Autorenwerkzeug selbst ableitbar sind. Können Bilder eingefügt werden, dann ist denke ich klar, dass das Werkzeug die Bereitstellung von Alternativtext als alt-Attribut anbieten muss. Wenn aber die erste Zeile eines Kommentars gefettet werden kann (quasi eine visuelle Überschrift) erwächst daraus schon die Verpflichtung für das Autorenwerkzeug (etwar Kommentarfunktion), ein eigenes Feld für die Überschrift anzubieten? Das ginge wohl zu weit?
=> 11.8.2 - Größeres Update für Barrierefreie Erstellung von Inhalten

Prüfschritte/de/9.1.4.3 Kontraste von Texten ausreichend.adoc
Absatz zum wünschenswerten Kontrast der Default-Seite bei Anbieten einer kontrastreicheren Ansicht über Styleswitcher gelöscht, da missverständlich.
=> Update 9.1.4.3 Kontraste von Texten ausreichend.adoc

Prüfschritte/de/9.1.1.1a Alternativtexte für Bedienelemente.adoc
Da die AGWG  mehrheitlich die Erfüllung von 1.1.1 über title akzeptiert (siehe https://github.com/w3c/wcag/issues/867 ) habe ich die Prüfung von Hintergrundbildern um die Erfüllung über title (und auch aria-label) ergänzt.
Im Schritt 2.1. "Anzeige der Alternativtexte von Grafiken" wird zurzeit nicht explizit das alt-Attribut verlangt, dehalb habe ich den Text hier unverändert gelassen. Man könnte hier noch hinzufügen, dass dies am besten durch das alt-Attribut geschieht, aber auch andere Techniken möglich sind.
=> Update 9.1.1.1a Alternativtexte für Bedienelemente.adoc

Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc
Änderung: Einstellung ist jetzt im Bereich "Surfen", Option "Markieren von Text mit der Tastatur zulassen"
Closes issue #53
=> Anpassung Auswahl 'Markieren'

Prüfschritte/de/7.1.1 Wiedergabe von Untertiteln.adoc
Ich habe denn Prüfschritt relativ breit (u.a. hinsichtlich Verständlichkeit) überarbeitet. Nicht klar war mir, weshalb bislang ein Unterschied gemacht wurde zwischen externen und eigenen Videos. Es geht im Web-Test ja um eingebundene Video-Player und nicht um Software (= Video-Player), daher habe ich das rausgenommen. Konnte in der EN dazu nichts finden.
Unter Hinweis gibt es derzeit noch den Bezug auf die Ausgabe in der Braille-Zeile. Dies ist keine "muss"-Anforderung in der EN, daher würde ich die eher rausnehmen, könnte missverständlich sein. Zumal wir keine Hinweise geben, wie man das prüft. Ist das vom Player abhängig?.
=> 7.1.1 überarbeitung ps beschreibung

Prüfschritte/de/7.1.3 Erhaltung von Untertiteln.adoc
Bitte gegenlesen.
Kann man noch Beispiele einfügen?
Was ist, wenn ein Video vor der Konvertierung keine Untertitel hatte? Sollte man das bei "Abgrenzung" erwähnen?
Betrifft parallel 7.2.3 "Erhaltung von Audiodeskription".
=> 7.1.3 erhaltung von untertiteln

Prüfschritte/de/5.2 Aktivierung von Barrierefreiheitsfunktionen.adoc
Änderungen:
- Anpassung an die übliche Struktur (noch nicht abgeschlossen)
- Hinweis zur Bestimmung der Zielgruppe
- Hinweis, was Identifizierbarkeit und Aktivierbarkeit praktisch bedeutet, mit zwei Beispielen
- Suche nach Barrierefreiheitsfunktionen aus Prüfanleitung entfernt (dafür in Anwendbarkeit explizit gemacht)
Hinweis / Frage: Die Formulierung in der EN deutet darauf hin, dass man nur Barrierefreiheit für "spezielle Bedürfnisse" prüft - ein Schalter für Leichte Sprache bräuchte ggf. keinen Alternativtext, "weil das ja nicht für die Blinden ist". Evtl. schießen wir also mit der Forderung "Bedienelemente erfüllen alle Anforderungen" über das intendierte Ziel dieser Anforderung hinaus.
=> Update 5.2 Aktivierung von Barrierefreiheitsfunktionen.adoc

Prüfschritte/de/6.2.2.3 Sprecheridentifizierung.adoc
Schritt "prüfen, ob die Web-App das Senden und Empfangen von Echtzeit
Textkommunikation anbietet" entfernt, da er schon in Anwendbarkeit des Prüfschrtts enthalten ist.
=> Update 6.2.2.3 Sprecheridentifizierung.adoc

Prüfschritte/de/6.2.2.4 Echtzeitindikation von Sprachkommunikation.adoc
Schritt "prüfen, ob die App Zwei-Wege-Sprachkommunikation unterstützt und Funktionen zur
Echtzeit-Textkommunikation bietet" entfernt, da das ja eigentlich im Schritt Anwendbarkeit enthalten ist.
=> Update 6.2.2.4 Echtzeitanzeige von Sprech-Aktivität

Prüfschritte/de/12.1.2 Barrierefreie Dokumentation.adoc
Änderung Prüfanleitung:
Hinweise zur Seitenauswahl gehören meiner Ansicht nach nicht in die Prüfanleitung, da die Seitenauswahl während der Prüfung bereits abgeschlossen ist. 
Daher habe ich entsprechende Texte in den Abschnitt "Hinweise" geschoben. Es verbleibt, die Prüfung ob im Verfahren für die Dokumentation alle Prüfschritte mit konform bewertet worden sind.
Es ist davon auszugehen, dass wenn die Seitenauswahl entsprechend des Prüfverfahrens durchgeführt wurde, die Dokumentation Teil der Seitenauswahl ist.
=> 12.1.2 Änderung Prüfanleitung

Prüfschritte/de/12.2.2 Technischer Support.adoc
- Anwendbarkeit ist nun begrenzt auf Angebote, die überhaupt Dokumentation zu Barrierefreiheits-Funktionen oder Hilfsmittel-Kompatibilität haben
- Hinzufügung von "Warum wird das geprüft?"
- Vereinfachung der Prüfung
- Abgrenzung des Prüfschritts von den Prüfungen in 12.2.3 und 12.2.4
=> Update 12.2.2 Technischer Support.adoc

Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc
Genauere Festlegung der Anwendbarkeit von 7.2.1 und Abgrenzung von der inhaltlichen Prüfung in 9.1.2.5 
Gibt es keine zusätzliche Version des Videos mit Audiodeskription, muss der Player auch keine Elemente zu deren Auswahl bereithalten.
=> Update 7.2.1 Wiedergabe von Audiodeskription.adoc

Prüfschritte/de/7.1.1 Wiedergabe von Untertiteln.adoc
Änderungen der Anwendbarkeit, Fokussierung des Prüfschritts auf Einbindungen von Videos mit separaten Untertiteln.
Änderung der prüfung, Wegfall der Prüfung vom Open Captions (eingebrannten Untertiteln). Fälle, in denen die Untertitel eingebrannt und immer sichtbar sind, brauchen sie auch nicht zuschaltbar zu sein.
=> Update 7.1.1 Wiedergabe von Untertiteln.adoc

Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc
Ein Listenelement mit nur 'Wenn' schien überflüssig.
=> 7.2.1: überflüssiges 'wenn'

Prüfschritte/de/7.1.1 Wiedergabe von Untertiteln.adoc
HTML 5 unterscheidet zwischen den Werten `subtitles` und `captions` für das `track`-Element. Siehe [track element in HTML 5.2](https://www.w3.org/TR/html52/semantics-embedded-content.html#the-track-element). EN 301 549 redet von "captions", nicht "subtitles".
=> 7.1.1: subtitles vs captions (kind-Attribute)

Prüfschritte/de/9.1.2.3 Audiodeskription oder Volltext-Alternative für Videos.adoc
Warum wird das geprüft: Deutlichere Formulierung, dass entweder AD oder Volltextalternativ als gültige Umsetzung möglich ist.
Anwendbarkeit: Deutlichere Formulierung, dass auch Volltext-Alternative nicht nötig ist, wenn Audiodeskription nicht gebraucht wird.
=> 9.1.2.3 Audiodeskritption oder Volltextalternative

Prüfschritte/de/7.1.3 Erhaltung von Untertiteln.adoc
=> 7.1.3: Tippfehler: sychnron

Prüfschritte/de/12.2.2 Technischer Support.adoc
Laut Diskussion in #172 ist der Prüfschritt nur anwendbar, wenn ein Unterstützungsdienst (Support) angeboten wird. Bisher war unklar, was bei Fehlen einer Kontaktmöglichkeit, aber Vorhandensein von technischer Dokumentation zu tun ist. Unser gegenwärtiges Verständnis der Anforderung deutet darauf hin, dass hier nicht grundsätzlich verlangt wird, dass jedes Webangebot technische Supportleistungen bietet.
=> 12.2.2 Genauere Bestimmung der Anwendbarkeit

Prüfschritte/de/12.2.3 Effektive Kommunikation.adoc
Ergänzt analog zu 12.2.2: Anwendbar nur für Angebote (etwa Web-Anwendungen) die explizit technischen Support anbieten.
=> Update 12.2.3 Effektive Kommunikation - Ergänzung Anwendbarkeit

Prüfschritte/de/9.2.4.2 Sinnvolle Dokumenttitel.adoc
Änderungen der Anforderungen an Seitentitel zur Anpassung an den normativen Text der WCAG: aussagekräftige Seitentitel ohne Nennung des Angebots können mit "eher erfüllt" bewertet werden (= sind konform),
Closes #200
=> Update 9.2.4.2 Sinnvolle Dokumenttitel.adoc

Prüfschritte/de/9.1.4.5 Verzicht auf Schriftgrafiken.adoc
Unter "Hinweise" Ausnahme für Schriftgrafiken, deren Informationsgehaltt im Kontext als Text verfügbar ist, erklärt (hier kann der Text als konforme Alternativversion gesehen werden - siehe Diskussion bei Issue https://github.com/w3c/wcag/issues/1647
=> Update 9.1.4.5 Verzicht auf Schriftgrafiken.adoc

Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc
Das Vokabular scheint seit dem 5.11.2021 umgezogen zu sein.
=> 12.1.1 Aktualisierung des URL zum aktuellen Accessibility-Vokabular

Prüfschritte/de/9.2.4.4 Aussagekräftige Linktexte.adoc
Wichtige Änderungen:
- Links die ggf. **für alle** unklar sind, fallen nicht unter diesen Prüfschritt. Das betrifft auch verlinkte E-Mail Adressen oder URLs
- Negativ bewertet wird fehlende Info zum Dateiformat in Links nur dann, wenn diese Info visuell vorhanden ist, aber nicht programmatisch
Bezugspunkte für die Überarbeitung sind Diskussionen in der Working Group - siehe zum Beispiel die längere Diskussion hier https://github.com/w3c/wcag/issues/1149 sowie mein PR https://github.com/w3c/wcag/pull/1164
=> 9.2.4.4 Grundlegende Überarbeitung "Aussagekräftige Linktexte"

Prüfschritte/de/11.7 Benutzerdefinierte Einstellungen.adoc
Verweis auf dark mode entfernt.
Siehe Diskussion in  #207 
Für Webangebote git der Browser als die Systemumgebung, deren Einstellungen übernommen werden sollen.
Dark mode ist eine Betriebssystemeinstellung, die hier deshalb missverständlich wäre.
Closes #207
=> Update 11.7 Benutzerdefinierte Einstellungen.adoc

Prüfschritte/de/9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc
Anpassung der Prüfanleitung für Icon fonts: "Falls kein Alternativtext über zugänglich versteckten oder mitverlinkten Text vorhanden ist.."
=> Update 9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc

Prüfschritte/de/9.1.4.1 Ohne Farben nutzbar.adoc
- Ausnahme korrigiert: Kontrast von Linkfarbe zur umgebenden Textfarbe muss 3,0:1 haben. Zum Hintergrund muss der Kontrast 4,5:1 sein (nicht wie es in dem Prüfschritt-Text stand 3,0:1).
- Abgrenzung zu diesem Prüfschritt ergänzt: Linkfarbe muss zum Hintergrund 4,5:1 haben. Wird bei 9.1.4.3 geprüft.
- Abgrenzung zu diesem Prüfschritt korrigiert: Wenn es gar keine Hervorhebung bei Links gibt, ist dies nicht nutzerfreundlich, wird aber in diesem Prüfschritt nicht negativ bewertet (auch nicht in Konsistente Navigation oder im Fokusprüfschritt - beide Verweise gelöscht).
=> 9.1.4.1 ohne farben nutzbar update

Prüfschritte/de/7.1.5 Gesprochene Untertitel.adoc
- Prüfschrittname geändert
- Anwendbar, wenn fremdsprachige Untertitel vorhanden sind.
- Warum wird das geprüft: Angepasst.
- FRAGE: Soll der Satz bei "Warum wird das geprüft "Sie können zum Beispiel als zusätzliche Tonspur oder über eine Text-to-Speech Funktionalität bereitgestellt werden." besser raus? Keinen Hinweis zur Umsetzung? Gibt es eine technisch bessere Formulierung?
=> 7.1.5 spoken subtitles

Prüfschritte/de/9.1.3.1a HTML-Strukturelemente für Überschriften.adoc
Vorschlag zur deutlicheren Formulierung, dass eine ausgelassene Überschriften Hierarchie-Ebenen keinen Fehler nach WCAG darstellt.
Auch wenn ich selbst dies immer als "best practice" in Prüfberichten anmerke, so ist das nach WCAG offiziell kein Fehler. 
Die bisherige Formulierung legt das immer noch nahe.
Siehe auch Artikel "Heading off confusion: When do headings fail WCAG?": 
https://www.tpgi.com/heading-off-confusion-when-do-headings-fail-wcag/
=> Update ausgelassene Überschriften Hierarchie-Ebenen kein Fehler nach WCAG

Prüfschritte/de/9.3.3.2 Beschriftungen von Formularelementen vorhanden.adoc
Anforderung bzgl. Erklärung des * etwas aufgeweicht: "Wenn zur Anzeige Symbole wie etwa ein Sternchen (*) genutzt werden, sollte deren Bedeutung erklärt sein (bestenfalls am Beginn des Formulars, bei einem mehrstufigen Formular beim ersten Formular)."
Siehe https://github.com/BIK-BITV/BIK-Web-Test/issues/33
=> Update 9.3.3.2 Beschriftungen von Formularelementen vorhanden.adoc

Prüfschritte/de/12.2.2 Technischer Support.adoc
- Der Erste Punkt in Prüfung (". Prüfen, ob das Webangebot einen Kontakt zu einem technischen Support anbietet.") kann entfallen, da schon in Anwendbarkeit abgedeckt.
- Ich habe Maja Benkes Vorschlag, die Anwendbarkeit in zwei Punkte zu gliedern, aufgegriffen, aber etwas nährer dran am Text der EN
Closes #191
=> 12.2.2 Technischer Support: Gliederung der "Anwendbarkeit" in zwei Punkte (Verbesserung der Verständlichkeit).adoc

Prüfschritte/de/9.1.4.3 Kontraste von Texten ausreichend.adoc
Styleswitcher-Element: Bei Beschriftung mit Text muss der Schalter einen Mindestkontrast von 4,5:1 erfüllen, bei grafischen Schaltern 3,0:1 vergl. 9.1.4.11. Siehe auch [issue](https://github.com/BIK-BITV/BIK-Web-Test/issues/13). Betrifft Abschnitt 2.2 und 3.2.
=> 9.1.4.3 Kontraste von Texten ausreichend: Konkretisierung hinsichtlich Styleswitcher-Element

Prüfschritte/de/9.3.3.3 Hilfe bei Fehlern.adoc
Unter Hinweise Ausnahme bzgl. Fehlermeldungen, die ein sicherheitsrisiko erzeugen würden, hinzugefügt.
Vorschlag: 
> Hinweise, wie genau der Fehler korrigiert werden kann, sind nicht erforderlich, wenn diese die Sicherheit des Inhalts gefährden würden. Zum Beispiel Anmelde- und Passwortfeldern müssen beispielsweise keine spezifischen Hinweise enthalten, da dies die Sicherheit des Anmeldevorgangs beeinträchtigen würden.
=> 9.3.3.3 Hilfe bei Fehlern: Ausnahme bei Sicherheitsrisiko.adoc

Prüfschritte/de/9.2.4.4 Aussagekräftige Linktexte.adoc
Frage zu diesem Prüfschritt entfernt.
Die Frage bezieht sich auf Mehrfachverlinkungen. Ich finde sie hier nicht so sinnvoll. Wenn, dann ist sie eher beim Prüfschritt "Sinnvolle Reihenfolge bei Tastaturbedienung" interessant, müsste dann aber aktualisiert werden und auf den neusten Stand der Empfehlungen gebracht werden.
=> 9.2.4.4 Aussagekräftige Linktexte: Frage zu Mehrfachverlinkungen entfernt

Prüfschritte/de/7.3 Bedienelemente für Untertitel und Audiodeskription.adoc
Anwendbarkeit korrigiert: Anwendbar, wenn UT / AD angeboten werden.
Vergleiche 7.1.1 Wiedergabe von Untertiteln und 7.1.2 Synchrone Untertitel: Bei beiden Prüfschritten ist das Vorhandensein von UT Voraussetzung für die Anwenbarkeit. Logisch wäre, dass das auch bei 7.3 gilt.
=> 7.3 Bedienelemente für Untertitel und Audiodeskription: Anwendbar, nur wenn UT / AD angeboten werden

Prüfschritte/de/7.1.1 Wiedergabe von Untertiteln.adoc
Anwendbarkeit des Prüfschritts aktualisiert / konkretisiert: Anwendbar, wenn Untertitel vorhanden sind (statt zuschaltbar).
Siehe EN-Formulierung: 
> Where ICT displays video with synchronized audio, it shall have a mode of operation to display the **available** captions.
=> 7.1.1 Wiedergabe von Untertiteln: Konkretisierung - Anwendbar, wenn Untertitel vorhanden sind (statt zuschaltbar)

Prüfschritte/de/11.8.4 Reparaturassistenz.adoc
Korrektur der Überschriftenstruktur der Prüfschrittbeschreibung ("3. Hinweise" = h3 statt h2).
=> 11.8.4 Reparaturassistenz: Korrektur der Überschriftenstruktur der Prüfschrittbeschreibung

Prüfschritte/de/9.3.3.1 Fehlererkennung.adoc
Ergänzung eines Hinweises, dass `aria-errormessage` zurzeit von Browsern noch nicht ausreichend unterstützt wird, um bei der Verknüpfung von Fehlermeldungen `aria-describedby` zu ersetzen.
closes #253
=> 9.3.3.1 Fehlererkennung: Zusätzlicher Hinweis hinsichtlich unzureichender Unterstützung von aria-errormessage

Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc
* Die Prüfung, ob Barrierefreiheitsfunktionen dokumentiert sind, war bislang auf Dokumentation im HTML-Format beschränkt. Da sich die inhaltliche Prüfung problemlos auch für Dokumentation in PDFs, Word usw. vornehmen lässt, wurde diese Eingrenzung auf HTML entfernt.
=> Update 12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc

Prüfschritte/de/5.4 Erhaltung von Barrierefreiheitsinformationen bei Konvertierung.adoc
* Da sich bei Konvertierung in nicht HTML-Formate das Zielformat nicht im BIK Web-Test prüfen lässt, ist die Prüfung auf Konvertierung mit HTML-Quell- und Zielformaten beschränkt. 
* Unter 3. Hinweise wurde ergänzt, dass Kunden in den Anmerkungen darauf hingewiesen werden sollten, dass Barriefrefrieheitsinformationen auch in Nicht-HTML Zielformaten erhalten bleiben sollen.
=> 5.4 Erhaltung von Barrierefreiheitsinformationen bei Konvertierung: Eingrenzung auf HTML-HTML-Konvertierung

Prüfschritte/de/9.2.2.1 Zeitbegrenzungen anpassbar.adoc
Anwendbarkeit geändert: Die Anwendbarkeit ist nicht nur auf Seiten mit Transaktionen beschränkt. Der Satz "...nur anwendbar auf Seiten mit Transaktionen, welche üblicherweise aus datenschutzrechtlichen oder sicherheitsrelevanten Gründen Zeitbegrenzungen unterliegen (etwa beim Online-Banking oder Online-Shops)." wurde entfernt.
=> 9.2.2.1 Zeitbegrenzungen anpassbar: Anwendbar, wenn Zeitbegrenzung gegeben (nicht nur bei Seiten mit Transaktion)

Prüfschritte/de/9.2.4.2 Sinnvolle Dokumenttitel.adoc
Tippfehlerkorrektur:
"Dokumenttitel bezeichnen den Inhalt der indiduellen Seiten" - > Dokumenttitel bezeichnen den Inhalt der individuellen Seiten
=> 9.2.4.2 Sinnvolle Dokumenttitel - Tippfehler-Korrektur

Prüfschritte/de/7.1.4 Untertitel-Anpassungen.adoc
Kleinere sprachliche Änderung, die keine inhaltliche Auswirkung hat.
=> 7.1.4 Untertitel-Anpassungen: Unbedeutende sprachliche Änderung

Prüfschritte/de/5.4 Erhaltung von Barrierefreiheitsinformationen bei Konvertierung.adoc
- Konvertierung meint Überführung in ein anderes Dateiformat. Der Hinweis, dass nur die Prüfung der Konvertierung von HTML-Quell- und Zielformat im Verfahren möglich sei, wurde entfernt, da es sich bei gleichem Quell- und Zielformat nicht um eine Konvertierung handelt.
- Die Prüfanleitung wurde erst einmal beibehalten, da die Prüfung ja grundsätzlich möglich ist, nur eben nicht in unserem Verfahren. Die Prüfanleitung wurde jedoch auch mit dem Hinweis ergänzt, dass in unserem Verfahren konvertierte Formate nicht geprüft werden können.
- Unter "3. Hinweise" wurde aufgenommen, dass der Prüfschritt auf "nicht anwendbar" gesetzt werden muss. Der Hinweis, dass dem Kunden in einer Anmerkung die Anforderung mitgegeben werden soll, wurde beibehalten.
=> 5.4 Erhaltung von Barrierefreiheitsinformationen bei Konvertierung: Anwendbarkeit bei Konvertierung von HTML-Ziel- und Quellformat entfernt

Prüfschritte/de/9.3.2.1 Keine unerwartete Kontextänderung bei Fokus.adoc
1. Anwendbarkeit des Prüfschritts: "Immer anwenbar" in "Anwendbar, wenn der Webauftritt interaktive Elemente enthält". (Konsistent zu "Fokus Order", "Focus Visible")
=> 9.3.2.1 Keine unerwartete Kontextänderung bei Fokus: Nicht anwendbar als Bewertungsoption ergänzt

Prüfschritte/de/9.2.1.1 Ohne Maus nutzbar.adoc
1. Anwendbarkeit des Prüfschritts: "Immer anwendbar" geändert in "Der Prüfschritt ist anwendbar, wenn der Webauftritt interaktive Elemente enthält." (Konsistent zu "Focus Order" und "Focus Visible")
=> 9.2.1.1 Ohne Maus nutzbar: Nicht anwendbar als Bewertungsoption ergänzt

Prüfschritte/de/9.1.4.5 Verzicht auf Schriftgrafiken.adoc
1. Anwendbar des Prüfschritts: Von "Immer anwendbar" auf "Anwendbar, wenn das Webangebot Schriftgrafiken enthält" geändert.
=> 9.1.4.5 Verzicht auf Schriftgrafiken: Nicht anwendbar als Bewertungsoption ergänzt

Prüfschritte/de/9.2.2.2 Bewegte Inhalte abschaltbar.adoc
Anpassung des letzten Punkts der Prüfung. Ist die Bewegung nach Stoppen nicht mehr erneut aktivierbar, ist das ggf. ein Bug und/oder ein Usability-Problem, aber keine normative Anforderung im Sinne dieses Prüfschritts.
=> 9.2.2.2 Bewegte Inhalte abschaltbar: Prüfung

Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc
Fehlendes Leerzeichen ergänzt.
=> 9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung: Korrektur: fehlendes Leerzeichen (ggftrotz)

Prüfschritte/de/9.3.3.2 Beschriftungen von Formularelementen vorhanden.adoc
Klärung, dass statt (Pflichtfeld) oder * auch das Ausweisen aller optionalen Felder möglich ist.
Closes #222
=> 9.3.3.2 Beschriftungen von Formularelementen vorhanden: Kennzeichnung von Pflichtfeldern über Ausweisen optionaler Felder

Prüfschritte/de/9.1.4.1 Ohne Farben nutzbar.adoc
Der Text zur Unterschiedung von Fließtextlinks nicht nur über Farbe wurde verallgemeinert auf "weiteres visuelles Merkmal": es muss nicht Fettung sein.
Closes #216
=> 9.1.4.1 Ohne Farben nutzbar: Verallgemeinerung

Prüfschritte/de/11.7 Benutzerdefinierte Einstellungen.adoc
- Stärker schrittweise Prüfanleitung
- Hinweis darauf, dass geänderte Vorder- und Hintergrundfarbe einen großen Kontrastabstand haben sollen.
- Konkretisierung, was bei benutzerdefinierten Farbeinstellungen geprüft wird: Wichtige Bedienelemente und Wahrnehmbarkeit von Zuständen von Formularelementen.
- Sollte man noch auf Wahrnehmbarkeit von Texten bei benutzerdefinierten Farben eingehen? 
- Bei "Nicht voll erfüllt" wurde folgendes entfernt (besser drin lassen?):
- Texte auf Grafiken kontrastieren nicht mehr ausreichend (es fehlt ein definierter Hintergrund)
- Schriften von Logos sind nicht mehr lesbar, weil sie einen transparenten Hintergrund haben
Closes #309
=> 11.7 Benutzerdefinierte Einstellungen: Konkretisierung der Prüfanleitung und Bewertung

Prüfschritte/de/9.1.4.12 Textabstände anpassbar.adoc
* Ergänzung eines Hinweises, dass die Anforderung nicht anwendbar ist auf Elemente wie `input type="file"`, auf die CSS-Anpassungen keine Auswirkung haben.
* Ergänzung eines Abschnitts "Bewertung"
Closes #325
=> 9.1.4.12 Textabstände anpassbar - Ausnahmen, Bewertung

Prüfschritte/de/9.2.1.1 Ohne Maus nutzbar.adoc
Änderungen im Abschnitt 3. Anmerkungen:
* Hinzufügung eines Hinweises, dass auch Elemente ohne sichtbare Fokushervorhebung geprüft werden (aus https://github.com/BIK-BITV/BIK-Web-Test/issues/270 )
* Leichte Umformulierung "Der Prüfer..." (Singular männlich)  -> "Prüfende..." (Plural)
* Umstellung der Reihenfolge der Anmerkungen
Closes #270
=> 9.2.1.1 Ohne Maus nutzbar: Ergänzung und kleine Korrekturen bei Anmerkungen

Prüfschritte/de/9.1.2.2 Aufgezeichnete Videos mit Untertiteln.adoc, Prüfschritte/de/9.1.2.3 Audiodeskription oder Volltext-Alternative für Videos.adoc
Der Abschnitt "Hinweis" der den Umstand erklärt, dass es ein A und AA-Kriterium für das Thema Audiodeskription gibt, war fälschlich 9.1.2.2 zugeordent. Er wurde bei 9.1.2.2 gelöscht und bei 9.1.2.3 eingefügt.
=> 9.1.2.3 Audiodeskription oder Volltext-Alternative für Videos - "Hinweis" von 9.1.2.2 nach 9.1.2.3 übertragen

Prüfschritte/de/7.1.5 Gesprochene Untertitel.adoc
7.1.5 Gesprochene Untertitel - Textkorrekturen, Ergänzung konkreter Bezeichnung "open captions" zur Vermeidung von Missverständlichkeit mangels fachlicher Bezeichnung
version:patch
changelog:fixed
=> 7.1.5 Gesprochene Untertitel - Textkorrekturen

Prüfschritte/de/9.1.3.2 Sinnvolle Reihenfolge.adoc
Der Prüfansatz, CSS abzuschalten und so die Reihenfolge der Inhalte zu überprüfen, ist oft nicht mehr sinnvoll. Die Prüfanleitung fokussiert deshalb auf das lineare Durchlaufen mit dem Screenreader, um Probleme der Reihenfolge und das Vorhandensein von nicht korrekt versteckten Inhalten zu ermitteln
=> 9.1.3.2 Sinnvolle Reihenfolge: Prüfung geändert

Prüfschritte/de/9.2.4.7 Aktuelle Position des Fokus deutlich.adoc
Bezüglich Messung des Kontrastunterschieds fokussiert/nichtfokussiert gab es bislang nur den Hinweis auf 9.1.4.3, der nur für Hervorhebungen über Änderungen ausschließlich über Textkontrastunterschied gelten würde (Anforderung 4.5:1). Ein Hinweis auf den Grafikkontraste-Prüfschritt 9.1.4.11 (hier Anforderung eines Kontrastunterschiedes von 3:1) wurde ergänzt.
=> 9.2.4.7 Aktuelle Position des Fokus deutlich - Bezug zu 9.1.4.11

Prüfschritte/de/9.1.3.1e Datentabellen richtig aufgebaut.adoc
'Quellen' wurden erweitert und aktualisiert:
* Link zu ARIA-Tabellen aktualisiert
* Artikel von Adrian Roselli über responsive Datentabellen hinzugefügt
* Artikel von Adrian Roselli über erweiterbare Datentabellen hinzugefügt
* Der Abschnitt "Quellen " wurde von den Abschntt "Einordnung des Prüfschritts" bewegt
=> 9.1.3.1e Datentabellen richtig aufgebaut: Quelle hinzugefügt

Prüfschritte/de/9.3.2.1 Keine unerwartete Kontextänderung bei Fokus.adoc
Fehlerhafte Verlinkung im Text korrigiert.
=> 9.3.2.1 Keine unerwartete Kontextänderung bei Fokus: Verlinkung korrigiert

Prüfschritte/de/9.2.4.6 Aussagekräftige Überschriften und Beschriftungen.adoc
Fehlerhafte Verlinkung im Text korrigiert.
=> 9.2.4.6 Aussagekräftige Überschriften und Beschriftungen: Verlinkung korrigiert

Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc
1. Fehlerhafte Verlinkung im Text korrigiert.
2. Verlinkung auf nicht mehr vorhandenes Ziel (?) entfernt. An anderen Stellen wird ebenfalls nicht auf die browsereigenes Entwicklerwerkzeug verlinkt.
=> 9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung: Verlinkungen korrigiert

Prüfschritte/de/9.2.2.2 Bewegte Inhalte abschaltbar.adoc
Ergänzung bei Bewertung: Nicht voll erfüllt: "Das Element zum Anhalten der Bewegung befindet sich nicht im unmittelbaren Kontext des sich bewegenden Elements oder am Beginn der Ansicht, oder erfüllt nicht alle Anforderungen der Barrierefreiheit."
=> 9.2.2.2 Bewegte Inhalte: Ergänzung Bewertung

Prüfschritte/de/9.4.1.1 Korrekte Syntax.adoc
Die Prüfung auf Syntax-Fehler fokussiert der Intention der AGWG zufolge allein auf inkorrekter Verschachtelung und doppelten IDs. Wir haben das "WCAG Parsing only" Bookmarklet, das auch Fehler nach dem HTML Content Model anzeigt, nun durch Christoph Strobbe's [WCAG Syntax Only Bookmarklet](https://cstrobbe.gitlab.io/A11yWorks/wcagtests/html5/sc_4.1.1_syntax/wcag-syntax-bookmarklet.html) ersetzt.
=> 9.4.1.1 Korrekte Syntax - Syntax-only Prüfung

Prüfschritte/de/9.1.4.1 Ohne Farben nutzbar.adoc
Neuer Abschnitt "3. Hinweise" zu zusätzlichen Möglichkeiten der Informationsvermittlung. 
Verdeutlichung des Hinweises, dass hinzukommende Formen (wie Umrandungen von Elementen bei Fokussierung) Informationen nicht ausschließlich durch Farbe vermitteln.
=> 9.1.4.1 Ohne Farben nutzbar - Hinweise zu zusätzlicher Informationsvermittlung

Prüfschritte/de/2.5.7 Ziehbewegungen.adoc
Neue Prüfschritt-Beschreibung 2.5.7 Ziehbewegungen, gültig für das erweiterte Prüfverfahren BITV-Test (+ WCAG 2.2)
=> 2.5.7 Ziehbewegungen: WCAG 2.2 - Neue Prüfschritt-Beschreibung

Prüfschritte/de/3.3.7 Redundanter Eintrag.adoc
Neue Prüfschrittbeschreibung für 3.3.7 Redundanter Eintrag für erweitertes Prüfverfahren BITV-Test (+ WCAG 2.2)
=> 3.3.7 Redundanter Eintrag: WCAG 2.2 - Neue Prüfschrittbeschreibung

Prüfschritte/de/9.3.2.6 Konsistente Hilfe.adoc
Korrektur: Fehlende Überschrift "Wie wird geprüft" ergänzt.
=> 9.3.2.6 Konsistente Hilfe: Ergänzung der fehlenden Überschrift "Wie wird geprüft"

Prüfschritte/de/9.2.4.6 Aussagekräftige Überschriften und Beschriftungen.adoc
In Mitten der Liste befand sich der String `=======`, durch welchen der Rest des Prüfschritts nicht richtig ausgegeben wurde. 
Soweit ich sehen konnte, ist das Überbleibsel eines misslungenen Merges, daher habe ich es einfach entfernt.
=> 9.2.4.6 Aussagekräftige Überschriften und Beschriftungen: Korrektur von Syntaxfehler

Prüfschritte/de/9.2.5.1 Alternativen für komplexe Zeiger-Gesten.adoc
Hinzufügung der Ausnahme für Bereiche mit CSS `overflow: scroll` (etwa bei Slidern), bei denen das Verhalten vom Betriebssystem oder Browser definiert wird und nicht von Web-Autoren.
=> Update 9.2.5.1 Alternativen für komplexe Zeiger-Gesten.adoc

Prüfschritte/de/9.2.5.8 Zielgröße (Minimum).adoc
* Ergänzung Prüfanleitung: Layout-Panel des Inspektors
* Erklärung, dass `padding` und `border` zur Zielgröße dazugehört
=> 9.2.5.8 Zielgröße (Minimum) - Ergänzungen

Prüfschritte/de/9.3.3.8 Zugängliche Authentifizierung (Minimum).adoc
* Löschung des ggf. missverständlichen Satzes "Sofern es keine Alternative gibt (beispielsweise die Bestätigung eines Vorgangs mithilfe eines Links oder einer Schaltfläche), wäre dies als Fehler im Sinne des Prüfschritts zu werten."
* Ergänzung Positivbeispiele: Anmeldung über OAuth Drittanbieter, biometrische Authentifizierung, und QR-Code-Scan
* Ergänzung Hinweise, 3.1: Beschränkung der Authentifizierung auf Anmeldung bei bestehenden Konten
* Ergänzung von Verifizierungs-Code (Einmal-Passcode)
* Ergänzung Hinweise, 3.2: Zwei-Faktor-Systeme, die nicht auf Codes beruhen, sind keine kognitiven Funktionstests
* Ergänzung Hinweise, 3.2: USB Security Tokens als Beispiel für Hardware-Authentifizierung
* Ergänzung Hinweise, 3.4: Beschränkung der Geltung für CAPCHA auf Fälle, wo diese als Teil …
=> 9.3.3.8 Zugängliche Authentifizierung (Minimum) - Ergänzungen

Prüfschritte/de/9.2.5.7 Ziehbewegungen.adoc
Zwei kleine Textänderungen: 
1. Anwendbar, sobald Ziehbewegungen implementiert sind, egal, ob sie genutzt werden **müssen** (das wäre ja ein Fail) oder Alternativen vorhanden sind.
2. Nicht nur Ziehen u. Ablegen (Drag'n Drop) sondern auch Verschieben, wo dieses nicht pfadgebunden ist
=> 9.2.5.7 Ziehbewegungen: Anwendbarkeit

Prüfschritte/de/9.2.4.7 Aktuelle Position des Fokus deutlich.adoc
Was wird geprüft:
* Löschung des Bezugs auf die Sichtbarkeit des Mausfokus (dass der Tastaturfokus mindestens so deutlich sein soll wie der Mausfokus, wird in den WCAG nicht verlangt)
* Hinweis, dass Tastaturfokus nicht aktiv unterdrückt werden darf
* Hinweis auf die Kontrastanforderung von 3:1 für die Fokushervorhebung.
Warum wird das geprüft:
* Löschung des Vergleiches mit Hervorhebung bei Mausnutzung
* Anpassung des Vergleichs mit Standard-Hervorhebung
Hinweise:
* Neuer Hinweis auf  Standard-Hervorhebung durch Browser 
Anwortet auf Issue https://github.com/BIK-BITV/BIK-Web-Test/issues/347
=> 9.2.4.7 Aktuelle Position des Fokus deutlich - Entfernung des Bezugs auf Hervorhebung bei Mausnutzung

Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc
Mit diesem PR soll der bestehende Text des Prüfschritts [9.2.4.3](https://bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-9-2-4-3-schluessige-reihenfolge-bei-der-tastaturbedienung) verdeutlicht werden in der Abgrenzung zu Prüfschritt [9.2.4.7](https://bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-9-2-4-7-aktuelle-position-des-fokus-deutlich) hinsichtlich der enthaltenen Phrase der "Stationen".
_Für die Vergabe von Labels habe ich keine Berechtigung, sodass ich rein die Änderungsvorschläge und die Beschreibung beigefügt habe._
=> 9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung: Verdeutlichung in der Abgrenzung zwischen 9.2.4.3 und 9.2.4.7

Prüfschritte/de/9.2.4.4 Aussagekräftige Linktexte.adoc
Hallo BITV!
Hier war der nicht existierende Prüfschritt 1.1.1.1b verlinkt
Nach dem Kontext muss hier auf "9.1.1.1b Alternativtexte für Grafiken und Objekte" verlinkt werden
LG & Schönes Wochenende 
Bastian
=> 9.2.4.4 Aussagekräftige Linktexte: Fix eines fehlerhaften Links

Prüfschritte/de/9.4.1.3 Statusmeldungen programmatisch verfügbar.adoc
Ergänzung der Prüfanleitung um die Prüfung, ob bei Anzeigen einer Statusmeldung die ganze Seite neu geladen wurde oder nicht (falls ja, ist der Prüfschritt nicht anwendbar).
=> 9.4.1.3 Statusmeldungen programmatisch verfügbar - Prüfanleitung

Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc
URL auf das bookmarket `Show Tab Focus` korregiert. 
Issue https://github.com/BIK-BITV/BIK-Web-Test/issues/462
=> Update 9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung: URL für `Show Tab Focus` Korrektur.

Prüfschritte/de/9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc
- Löschen der 80 Zeichen-Begrenzung
- Ergänzung, dass `alt` keine Strukturierungsmöglichekeiten bietet
=> 9.1.1.1b Alternativtexte für Grafiken und Objekte - 80 Zeichen

Prüfschritte/de/9.1.1.1d Alternativen für CAPTCHAs.adoc
Missing `T` for word `CAPTCHA` within the text.
=> 9.1.1.1d Alternativen für CAPTCHAs: Fehlendes T in CAPTCHA

Prüfschritte/de/9.1.3.1a HTML-Strukturelemente für Überschriften.adoc
A question should end with an `?` not with a `.`
Die Formatierung der ergänzenden Aussage `Es gibt doch klare formale Vorgaben für die richtige Strukturierung durch Überschriften!` könnte man ggf. optisch auch anders trennen, hat mMn keine inhaltliche Relevanz und könnte eventuell komplett entfernt werden. Die visuelle Darstellung lässt suggerieren, dass dieser Part ein Teil der Antwort und nicht der Frage ist.
=> 9.1.3.1a HTML-Strukturelemente für Überschriften: FAQ ? statt .

Prüfschritte/de/9.2.2.1 Zeitbegrenzungen anpassbar.adoc
- Anwendbarkeit: Die Prüfung auf Abschaltbarkeit oder Verlängerbarkeit ist immer anwendbar (war bislang auf Transaktionen ... beschränkt). Siehe https://github.com/BIK-BITV/BIK-Web-Test/issues/469
=> 9.2.2.1 Zeitbegrenzungen anpassbar - Anwendbarkeit überarbeitet (Beschränkung auf Transaktionen entfernt)

Prüfschritte/de/9.2.5.7 Ziehbewegungen.adoc
Anpassung der Prüfschrittanleitung, bzgl. 3. Beispiel (Schieberegler soll nicht im Vordergrund stehen), siehe https://github.com/BIK-BITV/BIK-Web-Test/issues/448
=> 9.2.5.7 Ziehbewegungen - Slider-Bezug beim letzen Beispiel in der Prüfschrittbeschreibung entfernt

Prüfschritte/de/9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar.adoc
- Abschnitt 3.2, Beispiel Datum mit 3 Auswahllisten: Text ergänzt (... "Datum" als Gruppenbeschriftung beispielsweise mit `fieldst` und `legend`. ...)
=> 9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar - Beispiel Datum: Ergänzung der Gruppenbeschriftung

Prüfschritte/de/9.2.4.1 Bereiche überspringbar.adoc
* Aktualisierung bezügl. nativer Bereichsauszeichnung
* Auszeichnung über Bereichsüberschriften als kaum noch gebräuchlich beschrieben
* Entfernen des Hinweises auf frames, übrig bleiben iframes
* Änderung der Reihenfolge der Prüfung (Bereichsüberschriften als Letztes)
* Fehlender title eines iframes kein FAIL, wenn sinnvolle Überschrift vorhanden
* Überarbeitung der Beispiele für erfüllt und nicht voll erfüllt
=> 9.2.4.1 Bereiche überspringbar - Überarbeitung

Prüfschritte/de/9.2.4.7 Aktuelle Position des Fokus deutlich.adoc
* Verweis auf 9.1.4.1 Ohne Farben nutzbar, was die Hervorhebung des Tastaturfokus über Farbwechsel angeht
* Entfernen eines Verweises auf das 1.4.11 Not-text Contrast Understanding Dokument bezügl. Fokushervorhebung durch Farbwechsel mit einem Kontrast von 3:1 oder besser (denn der Hinweis entfiel, dies wird nun hier explizit nicht geprüft, fällt aber unter 9.1.4.1 Ohne Farben nutzbar)
* Entfernen des Abgleichs mit Mausfokussierung von Links - denn die Anforderung gilt unabhängig von Hervorhebungen bei Maus-Hover und verwirrt hier eher
* Verschieben der Hinweise in Abschnitt 4. Bewertung / Erfüllt auf mögliche Fehler bei mangelndem Kontrast oder Nutzung on Farbwechseln in den Abschnitt 3. Hinweise
* Hinweis auf die Standard-Fokushervorhebung unter Bewertung / erfüllt
=> 9.2.4.7 Aktuelle Position des Fokus deutlich - Verweis auf 9.1.4.1 u.a.

Prüfschritte/de/9.1.4.1 Ohne Farben nutzbar.adoc
In den „FAQ“ wird innerhalb der Frage mit einem Satz begonnen, dessen Satzzeichen `.` fehlt. 
Man könnte die Frage aber ohne eine Aussage umformulieren etwa wie:
> Werden besuchte Links in einer anderen Farbe auch durch diesen Prüfschritt abgedeckt?
Da das aber eventuell ein zu starker Eingriff in die textliche Struktur ist, habe ich hier nur den fehlenden Punkt ersetzt, da dies meiner Einschätzung nach geändert werden sollte. Die Änderung des Textes empfinde ich als optional und würde ich den Author*innen überlassen.
=> 9.1.4.1 Ohne Farben nutzbar: Fehlendes Satzzeichen in FAQ

Prüfschritte/de/9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc
1. Referencing for `2.6 Angemessene Alternativetexte` were not working , since its `2.7` instead of `2.6`. 
2. `2.6 Angemessenheit von Textalternativen im Kontext` after `2.7` is not correct, since its after `2.7` it should be `2.8 Angemessenheit von Textalternativen im Kontext`
=> <9.1.1.1b> Alternativtexte für Grafiken und Objekte.adoc: Fix anchor links and order numbers

Prüfschritte/de/9.2.2.1 Zeitbegrenzungen anpassbar.adoc
- Typo in „Statusmeldungen“
- Typo „Weise“
- Aufzählung von mehreren Ereignissen führt zur Verwendung von Plural (`erfolgt` → `erfolgen`) 
- `Ein` webbasierter E-Mail-Client statt `Eine` [...]
=> 9.2.2.1 Zeitbegrenzungen anpassbar: Typo

Prüfschritte/de/9.2.5.7 Ziehbewegungen.adoc
Die Aktualisierung der [single pointer Definition](https://www.w3.org/TR/WCAG22/#dfn-single-pointer) in den WCAG führt zu einer leichten Textänderung: Die Rede ist jetzt von "Eingabe über einfachen Zeiger ohne Ziehbewegung"
=> 9.2.5.7 Ziehbewegungen: Anpassung an "einfache Zeiger"

Prüfschritte/de/9.2.4.7 Aktuelle Position des Fokus deutlich.adoc
- "Was wird geprüft": Hinweis auf Kontrastprüfung der Fokushervorhebung in diesem Prüfschritt entfernt. Wird seit dem vorletzten Release entsprechend WCAG bei 9.1.4.11 geprüft. In der Prüfanleitung wird die Abgrenzung bereits richtig dargestellt.
=> 9.2.4.7 Aktuelle Position des Fokus deutlich - Hinweis zu Kontrastanforderung bei "Was wird geprüft" entfernt

Prüfschritte/de/9.1.4.12 Textabstände anpassbar.adoc
- Hinweis und Ausnahme deutlicher gemacht.
- HTML-Standardelemente wie file-upload und Ausklapplisten (select > option) sind ausgenommen.
- Verlinkung zur Definition einer Ausklappliste
=> 9.1.4.12 Textabstände anpassbar: Ergänzung der Ausname "Auswahliste" (select > option) (version:minor)
