Prüfschritte/de/11.8.3 Erhaltung von Barrierefreiheitsinformationen bei Transformation.adoc

Hauptsächlich editorische Änderungen. Bitte um Hilfe über Gtihub Issues unter die Prüfanleitung geschoben.

11.8.3 Erhaltung von Barrierefreiheitsinformationen bei Transformation

---

Prüfschritte/de/11.8.5 Vorlagen.adoc

11.8.5 Umformulierung von Anwendbarkeit und Prüfung

11.8.5 Vorlagen - Umformulierung

---

Prüfschritte/de/9.2.2.2 Bewegte Inhalte abschaltbar.adoc

Ausnahmen sind jetzt im Abschnitt "1. Anwendbarkeit des Prüfschritts" genannt.
Closes #18

2.2.2 update (Ausnahmen)

---

Prüfschritte/de/5.2 Aktivierung von Barrierefreiheitsfunktionen.adoc

Closes #11.
@JohannesFischer84 vielen Dank für die Beispiele.

5.2: Beispiele für Barrierefreiheitsfunktionen und Identifizierbarkeit hinzugefügt.

---

Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc

12.1.1: Beispiele für Barrierefreiheitsfunktionen und -Eigenschaften hinzugefügt.

---

Prüfschritte/de/9.3.1.2 Anderssprachige Wörter und Abschnitte ausgezeichnet.adoc

In Prüfschritt 3 Ausnahmen explizit erwähnt (es gibt dann Verlinkung auf Hinweise mit ausführlichen Angaben)
Closes #46

Ergänzung Ausnahmen Sprachauszeichnung

---

Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc

7.2.1 überarbeitung ps beschreibung

---

Prüfschritte/de/6.2.2.4 Echtzeitindikation von Sprachkommunikation.adoc

Ich denke, Der Titel "Echtzeitanzeige von Sprech-Aktivität" sagt genauer, worum es hier geht.

Update 6.2.2.4 Echtzeitindikation von Sprachkommunikation.adoc

---

Prüfschritte/de/7.3 Bedienelemente für Untertitel und Audiodeskription.adoc

Vereinfachte Umformulierung der Prüfung Punkt 3

Update 7.3 Bedienelemente für Untertitel und Audiodeskription.adoc

---

Prüfschritte/de/7.1.1 Wiedergabe von Untertiteln.adoc

Anpassung an die vorgegebene Struktur.

7.1.1 Einordnung des Prüfschritts

---

Prüfschritte/de/6.2.1.1 Textkommunikation in Echtzeit.adoc

Update 6.2.1.1 Textkommunikation in Echtzeit.adoc

---

Prüfschritte/de/7.1.1 Wiedergabe von Untertiteln.adoc

Hinzugefügte Abgrenzung - Kontrast, Tastaturbedienbarkeit usw. werden in anderen Prüfschritten bewertet.

Update 7.1.1 Wiedergabe von Untertiteln.adoc

---

Prüfschritte/de/7.1.2 Synchrone Untertitel.adoc

Update 7.1.2 Synchrone Untertitel.adoc

---

Prüfschritte/de/6.2.3 Interopabilität von Echtzeit-Textkommunikation.adoc

* Anpassung an das etablierte Format
* Umformulierung der Prüfschritt-Beschreibung, Entfernung des ersten Punktes (kommt schon bei der Prüfung der Anwendbarkeit)

Update 6.2.3 Interopabilität von Echtzeit-Textkommunikation.adoc

---

Prüfschritte/de/5.3 Biometrie.adoc

Änderungen der Neuformulierung:
- Stärkere Betonung der nicht-biometrischen Alternativen (i.d.R. gibt es ja traditionelle Methoden wie Pin oder Passworteingabe, und Biometrie wird zusätzlich eingesetzt).
- Hinzufügung von 3. Hinweise, Qualifizierung biometrischer Steuerung: meist Authentifizierung innerhalb von Prozessen, Hinweise auf andere Möglichkeiten
- Hinzufügung von Bewertungsoptionen

Update 5.3 Biometrie.adoc

---

Prüfschritte/de/6.1 Audiobandbreite für Sprache.adoc

Änderungen:
Anpassung an das übliche Format

Update 6.1 Audiobandbreite für Sprache.adoc

---

Prüfschritte/de/6.5.2 Auflösung bei Videotelefonie.adoc

* Anpassung an das gängige Prüfschrittformat
* Anpassug der Püfschrittbeschreibung

Update 6.5.2 Auflösung bei Videotelefonie.adoc

---

Prüfschritte/de/6.2.1.2 Gleichzeitige Sprache und Text.adoc

Änderungen:
- Anpassungen an das bekannte Format
- Kürzung der Prüfung (erster Punkt war schon implizit in Anwendbarkeit)
Präzisierung der Anforderungen, Hinweis auf Handheben und gemeinsame Warteschlange

Update 6.2.1.2 Gleichzeitige Sprache und Text.adoc

---

Prüfschritte/de/6.3 Anrufer-Identifizierung.adoc
Prüfschritte/de/6.3 Anrufidentifizierung.adoc

Anpassung ans übliche Prüfschrittformat

Update 6.3 Anrufer-Identifizierung.adoc

---

Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc

- Keine Inhaltliche Überarbeitung
- Nur Anpassung der Struktur

Update 12.1.1 Anpassung an die Struktur

---

Prüfschritte/de/12.1.2 Barrierefreie Dokumentation.adoc

- Noch keine inhaltliche Änderungen.
- Nur Anpassung an die Struktur.

12.1.2 Anpassung an die Struktur

---

Prüfschritte/de/12.2.2 Technischer Support.adoc

- Noch keine inhaltliche Überarbeitung
- Nur Anpassung an die Struktur.

12.2.2 Anpassung an die Struktur

---

Prüfschritte/de/12.2.3 Effektive Kommunikation.adoc

- Noch keine inhaltliche Überarbeitung
- Nur Anpassung an die Struktur

12.2.3 Anpassung an die Struktur

---

Prüfschritte/de/12.2.4 Vom Support bereitgestellte Dokumentation.adoc

- Keine inhaltliche Änderungen
- Nur Anpassung an die Struktur

12.2.4 Anpassung an die Struktur

---

Prüfschritte/de/11.8.5 Vorlagen.adoc

- Keine inhaltliche Überarbeitung
- nur kleinere sprachliche Anpassungen

11.8.5 Anpassung an die Struktur

---

Prüfschritte/de/11.8.4 Reparaturassistenz.adoc

- Keine Inhaltliche Änderungen
- Nur Anpassung an die Struktur und sprachliche Änderungen "Was wird geprüft".

11.8.4 Anpassung an die Struktur

---

Prüfschritte/de/12.1.2 Barrierefreie Dokumentation.adoc

- Neuer Abschnitt "Warum"
- Umgestaltuing Prüfung, expliziter Hinweis auf Erklärung zur Barrierefreiheit
- Logik "Mitprüfen, wenn andere PS erfüllt alle, dann auch dieser PS erfüllt" (sonst nicht)

"Warum..." hinzugefügt

---

Prüfschritte/de/5.3 Biometrie.adoc

Beispiele für biometrische Merkmale unter "Was wird geprüft" hinzugefügt.

5.3 Beispiele für biometrische Merkmale eingefügt

---

Prüfschritte/de/9.1.3.4 Keine Beschränkung der Bildschirmausrichtung.adoc

* Hinweis auf spezifische Größe des Mobilgeräts für die Prüfung entfernt
* Prüfablauf in Punkte untergliedert und leicht angepasst
Closes #130

Gliederung, Generalisierung

---

Prüfschritte/de/7.1.2 Synchrone Untertitel.adoc

- Stichprbenartige Prüfung der Untertitel zuzugefügt.

7.1.2 Prüfung Untertitel-Datei

---

Prüfschritte/de/9.1.3.1c HTML-Strukturelemente für Zitate.adoc

Vereinfachung der Kommentare zum q-Element.

Update 9.1.3.1c HTML-Strukturelemente für Zitate.adoc

---

Prüfschritte/de/9.2.5.1 Alternativen für komplexe Zeiger-Gesten.adoc

Klarere Unterscheidung zwischen pfadbasierten Gesten und Ziehbewegungen (dragging motions)

Update 9.2.5.1 Alternativen für komplexe Zeiger-Gesten.adoc

---

Prüfschritte/de/12.2.3 Effektive Kommunikation.adoc

- Abschnitt "Warum wird das geprüft?" hInzugefügt.

Update 12.2.3 Effektive Kommunikation.adoc

---

Prüfschritte/de/12.2.4 Vom Support bereitgestellte Dokumentation.adoc

- Abschnitt "Warum wird das geprüft?" hinzugefügt.

Update 12.2.4 Vom Support bereitgestellte Dokumentation.adoc

---

Prüfschritte/de/6.2.2.2 Programmatisch unterscheidbare Anzeige von Textnachrichten.adoc

anznehmen -> anzunehmen sein
emfangen... -> empfangen...

6.2.2.2: Tippfehler

---

Prüfschritte/de/6.5.2 Auflösung bei Videotelefonie.adoc

Web-Anwendung -> Web-Anwendungen

6.5.2: Tippfehler

---

Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc

7.2.1: Tippfehler: givt

---

Prüfschritte/de/12.1.2 Barrierefreie Dokumentation.adoc

- Neue Formulierung der Prüfung der Dokumentation: als Teil der Seitenauswahl / nicht Teil der Seitenauswahl
- Hinweise ergänzt (wann kann darauf verzichtet werden, die Dokumentation in die Seitenauswahl zu nehmen?)

Update 12.1.2 barrierefreie dokumentation

---

Prüfschritte/de/11.7 Benutzerdefinierte Einstellungen.adoc

Absatz unter "Nicht voll erfüllt" angepasst

Update 11.7 Benutzerdefinierte Einstellungen.adoc

---

Prüfschritte/de/12.1.2 Barrierefreie Dokumentation.adoc

- Warum wird geprüft: Widersprüche aus der letzten Fassung bereinigt
- Prüfung: Einleitender Satz hinzugefügt.

12.1.2 Barrierfreie Dokumentation

---

Prüfschritte/de/12.1.2 Barrierefreie Dokumentation.adoc

Schwer verständliche Formulierung in "Anwendbarkeit des Prüfschritts" vereinfacht

Update 12.1.2-Vereinfachung Anwendbarkeit

---

Prüfschritte/de/9.3.3.1 Fehlererkennung.adoc

Behebt einen kleinen Fehler in einem Satz.

Kleiner Fehler in Prüfschritt 9.3.3.1

---

Prüfschritte/de/6.5.4 Synchronität bei Videotelefonie.adoc

- Kleinere redaktionelle Anpassungen
- Github-Link zu Hinweise verschoben (Konsistenz mit anderen Prüfschritten).

Update 6.5.4 Synchronität bei Videotelefonie.adoc

---

Prüfschritte/de/9.1.3.1e Datentabellen richtig aufgebaut.adoc

Ergänzung der Prüfung von mit ARIA ausgezeichneten Tabellen.
- Erweiterung Anwendbarkeit um visuell als Datentabelle strukturierte Inhalte und solche Tabellen, die ARIA statt nativem Markup nutzen
- Ergänzung Prüfung
- Ergänzung Quellen

9.1.3.1c Ergänzung der Prüfung für ARIA-Datentabellen

---

Prüfschritte/de/9.1.3.1a HTML-Strukturelemente für Überschriften.adoc

* Ergänzung von ARIA-markup bei Was wird geprüft
* Bessere Berücksichtigung von ARIA-markup bei 2. Prüfung
* Anpassung von 4. Bewertung zur Berücksichtigung der Erfüllung über ARIA-Mark-Up

9.1.3.1a Bessere Integration von ARIA role=heading und aria-level in Prüfung

---

Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc

9.2.4.3 tabreihenfolge redaktionelles update

---

Prüfschritte/de/6.5.6 Sprecher-Anzeige für Gebärdensprachen-Kommunikation.adoc

- Redaktionelle Änderungen
- Github-Link zu Hinweise verschonben.

Update 6.5.6 Sprecher-Anzeige für Gebärdensprachen-Kommunikation.adoc

---

Prüfschritte/de/6.4 Alternativen zu sprachbasierten Diensten.adoc

Redaktionelle Änderung, u.a. Verwendung der Bezeichnung "interaktive Sprachdialogsysteme".

6.4. alternative zu sprachbasierten diensten update

---

Prüfschritte/de/9.4.1.3 Statusmeldungen programmatisch verfügbar.adoc

9.4.1.3 statusmeldungen sw

---

Prüfschritte/de/6.5.4 Synchronität bei Videotelefonie.adoc

Bei den Zielgruppen im Abschnitt "Warum wird das geprüft?" werden bisher nur kognitiv eingeschränkte Menschen erwähnt. Bezüglich Höreinschränkungen gibt es jedoch ebenfalls Nutzen von synchronem Bild und Ton. Siehe Änderungs-Dokument.
Bei Zustimmung könnte das ebenso im gleichen Prüfschritt des App-Tests eingefügt werden.

6.5.4 Synchronität Videotelefonie - Anpassung Warum wird das geprüft

---

Prüfschritte/de/9.4.1.2 Name-Rolle-Wert verfügbar.adoc

Link auf ARIA Authoring Practices Guide aktualisiert. Siehe #267

Update 9.4.1.2 Name-Rolle-Wert verfügbar.adoc

---

Prüfschritte/de/7.1.4 Untertitel-Anpassungen.adoc

Ergänzung Erfüllung über Anpassbarkeit über Browser-Einstellungen.
Normativ legt die EN Anfoderung 7.1.4 nicht nur nicht fest, welche Anpassungsmöglichkeiten erforderlich sind; sie legt auch nicht fest, **auf welche Weise** ICT die Anpassungen der Untertitel zu unterstützen hat. 
Ein üblicher Weg ist die Anpassung über Einstellungen im Player. Wenn jedoch Änderungen von Einstellungen im Browser, wie eine höhere Mindestschriftgröße oder ein eigenes Farbschema, sich auf die Darstellung der Untertitel auswirken, ist der Prüfschritt ebenfalls als erfüllt zu betrachten.

7.1.4 Untertitel-Anpassungen: Erfüllen über Browseranpassung

---

Prüfschritte/de/12.1.2 Barrierefreie Dokumentation.adoc

* Ergänzung: Produkt-Dokumentation wurde definiert als technische Dokumentation des Angebots, abgegrenzt von inhaltlicher Hilfe im Angebot, etwa in FAQs.

Update 12.1.2 Barrierefreie Dokumentation.adoc

---

Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc

9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung: Tippfehler-Korrektur

---

Prüfschritte/de/7.1.5 Gesprochene Untertitel.adoc

Hinzufügung einer Quelle der ITU (T.701.25, eine kostenlose Fassung von ISO - ISO/IEC TS 20071-25:2017 - Information technology - User interface component accessibility - Part 25: Guidance on the audio presentation of text in videos, including captions, subtitles and other on-screen text

7.1.5 Gesprochene Untertitel: Hinzufügung einer ITU-Quelle mit Umsetzungsempfehlungen

---

Prüfschritte/de/9.1.1.1a Alternativtexte für Bedienelemente.adoc

Überarbeitung und Kürzung des Abschnittes "Fragen zu diesem Prüfschritt".
* Ergänzung von Hinweisen für Bilder in verlinkten Teasern
* Kürzung von Dateinamen als Alternativtexte
* Kürzung nder Hinweise zur Verwnedugn des `title`-Attributs

9.1.1.1a Alternativtexte für Bedienelemente: Überarbeitung "Fragen zu diesem Prüfschritt"

---

Prüfschritte/de/9.1.4.3 Kontraste von Texten ausreichend.adoc

Korrektur URLs zur Werkzeugliste

9.1.4.3 Kontraste von Texten ausreichend - Korrektur von URLs

---

Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc

URL aktualisiert auf https-Protokoll.

9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung: Korrektur von URLs

---

Prüfschritte/de/9.4.1.1 Korrekte Syntax.adoc

Aktualisierung einer URL (auf https-Protokoll)

Update 9.4.1.1 Korrekte Syntax.adoc

---

Prüfschritte/de/9.1.4.11 Kontraste von Grafiken und grafischen Bedienelementen ausreichend.adoc

- Korrektur eines Tippfehlers
- Reparatur eines Links

9.1.4.11 Kontraste von Grafiken und grafischen Bedienelementen ausreichend: Korrektur eines Tippfehlers und Reparatur eines Links

---

Prüfschritte/de/7.1.1 Wiedergabe von Untertiteln.adoc

* Ergänzt: MDN Quelle "Adding captions and subtitles to HTML video"

7.1.1 Wiedergabe von Untertiteln: Hinzufügung einer Quelle

---

Prüfschritte/de/9.2.2.2 Bewegte Inhalte abschaltbar.adoc

1. Anwendbarkeit des Prüfschritts: Mit zwei Absätze gegliedert. Umstellung des ersten Satzes.

9.2.2.2 Bewegte Inhalte abschaltbar: Kleinere redaktionelle Optimierung

---

Prüfschritte/de/6.2.1.1 Textkommunikation in Echtzeit.adoc

Ergänzung der Quelle "WebRTC 1.0: Real-Time Communication Between Browsers. W3C Editor's Draft 06 February 2023"

6.2.1.1 Textkommunikation in Echtzeit: Ergänzung Quelle

---

Prüfschritte/de/9.1.2.5 Audiodeskription für Videos.adoc

* Hinzufügung einer Frage zu diesem Prüfschritt: Was sind "wichtige informationstragende Bildinhalte"? 
* Präzisierung der Prüfung (Verweis auf  "wichtige informationstragende Bildinhalte")

9.1.2.5 Audiodeskription für Videos: Ergänzung Frage

---

Prüfschritte/de/9.1.3.4 Keine Beschränkung der Bildschirmausrichtung.adoc

9.1.3.4 Keine Beschränkung der Bildschirmausrichtung - Textkorrekturen
version:patch
changelog:fixed

9.1.3.4 Keine Beschränkung der Bildschirmausrichtung - Textkorrekturen

---

Prüfschritte/de/7.1.4 Untertitel-Anpassungen.adoc

Korrektur Rechtschreibfehler "Schriftgöße".
version:patch
changelog:fixed

7.1.4 Untertitel-Anpassungen: Korrektur Rechtschreibfehler

---

Prüfschritte/de/9.1.3.4 Keine Beschränkung der Bildschirmausrichtung.adoc

9.1.3.4 Keine Beschränkung der Bildschirmausrichtung - Textkorrektur
version:patch
changelog:fixed

9.1.3.4 Keine Beschränkung der Bildschirmausrichtung - Textkorrektur

---

Prüfschritte/de/9.1.3.2 Sinnvolle Reihenfolge.adoc

Anpassung der Prüfanleitung (und Bewertung), stärker auf Quelltextanalyse bezogen.

Sweckenmann patch 1

---

Prüfschritte/de/11.7 Benutzerdefinierte Einstellungen.adoc

11.7 Benutzerdefinierte Einstellungen: Korrektur von Rechtschreibfehlern

---

Prüfschritte/de/9.1.4.5 Verzicht auf Schriftgrafiken.adoc

Fehlerhafte Verlinkungen im Text korrigiert.

9.1.4.5 Verzicht auf Schriftgrafiken: Verlinkungen korrigiert

---

Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc

Hinzufügung einer Quelle (Artikel von Knowbility zur Fokusbehandlung bei Slide-out Menüs)

9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung: Quelle

---

Prüfschritte/de/9.1.3.2 Sinnvolle Reihenfolge.adoc

Korrigiert einzelnes Wort
`changelog:fixed`
`version:patch`

9.1.3.2 Sinnvolle Reihenfolge: Korrektur von Rechtschreibfehler

---

Prüfschritte/de/2.5.8 Zielgröße (Minimum).adoc

Neue Prüfschrittbeschreibung für 2.5.8 Zielgröße Minimum für das erweiterte Prüfverfahren BITV-Test (+ WCAG 2.2)

2.5.8 Zielgröße (Minimum): WCAG 2.2 - Neue Prüfschritt-Beschreibung

---

Prüfschritte/de/3.2.6 Konsistente Hilfe.adoc

Neue Prüfschrittbeschreibung für 3.2.6 Konsistente Hilfe, gilt für das erweiterte Prüfverfahre BITV-Test (+ WCAG 2.2)

3.2.6 Konsistente Hilfe: WCAG 2.2 - Neue Prüfschritt-Beschreibung

---

Prüfschritte/de/3.3.8 Zugängliche Authentifizierung (Minimum).adoc

Neue Prüfschritt-Beschreibung für 3.3.8 Zugängliche Authentifizierung für das erweiterte Prüfverfahren BITV-Test (+ WCAG 2.2)

3.3.8 Zugängliche Authentifizierung (Minimum) - WCAG 2.2 Neue Prüfschritt-Beschreibung

---

Prüfschritte/de/9.2.4.11 Fokus nicht verdeckt (Minimum).adoc

Überschrift "Warum wird das geprüft" ergänzt, "Wie wird geprüft" an anderes Stelle gesetzt.

9.2.4.11 Fokus nicht verdeckt (Minimum): Korrektur der Überschriften(formatierung)

---

Prüfschritte/de/5.2 Aktivierung von Barrierefreiheitsfunktionen.adoc

Sammler für weitere marginale Rechtschreibaspekte.

Verschiedene Prüfschritte: Rechtschreibung

---

Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc

* Egänzung von Abschnitt Bewertung.

12.1.1 Dokumentation von Kompatibilität u. Barrierefreiheit - Ergänzung Bewertung

---

Prüfschritte/de/9.3.2.6 Konsistente Hilfe.adoc

Ergänzung 3. Hinweise: Ein Hilfemechanismus kann sich auf manchen Seiten in einem Aufklappelement befinden.

9.3.2.6 Konsistente Hilfe - Aufklappelement

---

Prüfschritte/de/9.1.4.11 Kontraste von Grafiken und grafischen Bedienelementen ausreichend.adoc

Neuer Punkt 2.5: Ergänzung der Prüfung einer Styleswitcher-Ansicht (analog zu 9.1.4.3)

9.1.4.11 Kontraste von Grafiken u. grafischen Bedienelementen…Styleswitcher-Prüfung

---

README.md

- Ergänzung von Nutzungsbedingungen und Markenschutz

README - Ergänzung von Nutzungsbedingungen und Markenschutz

---

Prüfschritte/de/9.1.3.1d Inhalt gegliedert.adoc

Korrektur eines Rechtschreibfehlers.

9.1.3.1d Inhalt gegliedert: Korrektur von Rechtschreibfehler

---

Prüfschritte/de/9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc

1. **Benennung des Pull Requests** nach dem Schema `<Prüfschritt-Nummerierung> <Prüfschritt-Bezeichnung>: <Kurzbeschreibung-Änderung>`, beispielsweise "9.1.1.1a Alternativtexte für Bedienelemente: Korrektur von Rechtschreibfehlern".
2. **Vergabe eines `version:*`-Labels** zur Kenntlichmachung, wie gravierend der Pull Request das Prüfverfahren beeinflusst (Standard: `version:patch`).
3. **Vergabe eines `changelog:*`-Labels**, um die Darstellung des Pull Requests im Änderungsprotokoll zu steuern.
Ausführliche Hinweise finden Sie in der [Anleitung zur Mitwirkung](/BIK-BITV/BIK-Web-Test/blob/doc/CONTRIBUTING.md). Sie können diese Beschreibung löschen oder durch eine Erläuterung ihrer Änderungsvorschläge ersetzen.

9.1.1.1b Alternativtexte für Grafiken und Objekte: Tippfehler-Korrektur

---

Prüfschritte/de/9.1.3.2 Sinnvolle Reihenfolge.adoc

9.1.3.2 Sinnvolle Reihenfolge.adoc: Tippfehler-Korrektur

---

Prüfschritte/de/9.1.4.1 Ohne Farben nutzbar.adoc

9.1.4.1 Ohne Farben nutzbar: fehlende Klammer

---

Prüfschritte/de/9.2.4.1 Bereiche überspringbar.adoc

9.2.4.1 Bereiche überspringbar: typo

---

Prüfschritte/de/9.1.3.5 Eingabefelder zu Nutzerdaten vermitteln den Zweck.adoc

9.1.3.5 Eingabefelder zu Nutzerdaten vermitteln den Zweck: typo

---

Prüfschritte/de/9.1.4.1 Ohne Farben nutzbar.adoc

Ergänzung: 
- Fokushervorhebung nur mithilfe von Farbänderung umgesetzt: Bewertung erfolgt in diesem Prüfschritt

Update 9.1.4.1 Ohne Farben nutzbar - Prüfung eines Fokusindikators, der nur mithilfe von Farbänderung umgesetzt ist

---

Prüfschritte/de/9.2.5.8 Zielgröße (Minimum).adoc

Kleinere Anpassungen des Textes (z.B. Ersetzung des Begriffs "Zeigegerät").

9.2.5.8 Zielgröße (Minimum): Textanpassung

---

Prüfschritte/de/9.3.2.6 Konsistente Hilfe.adoc

9.3.2.6 Konsistente Hilfe: Typo

---

Prüfschritte/de/9.2.4.11 Fokus nicht verdeckt (Minimum).adoc

9.2.4.11 Fokus nicht verdeckt (Minimum) - kleine Texänderungen

---

Prüfschritte/de/9.2.5.2 Zeigergesten-Eingaben können abgebrochen oder widerrufen werden.adoc

Ergänzung des Desktop-Tests (es wird nicht nur auf dem mobilen Gerät getestet).

9.2.5.2 Zeigergesten-Eingaben (...) - Test auf Desktop ergänzt
